# Generated by Django 4.0.5 on 2022-06-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oylar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ustozlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
                ('number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('number', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('price', models.SmallIntegerField(choices=[(1, "Tulov bo'ldi"), (2, 'Qarzi bor'), (3, 'Qilinmagan')])),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.guruh')),
                ('oy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.oylar')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='ustoz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ustozlar'),
        ),
    ]
