# Generated by Django 4.0.5 on 2022-06-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_oylar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='kurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kurs'),
        ),
    ]
